grails-app/domain/ar/piwaf/Post.groovy
package ar.piwaf

class Post {
	String titulo
	String autor
	String contenido
	Date dateCreated
    static constraints = {
		titulo()
		autor()
		contenido(nullable: true, maxSize:500)
    }
}

grails-app/controllers/ar/piwaf/PostController.groovy
package ar.piwaf



import static org.springframework.http.HttpStatus.*
import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured("ROLE_ADMIN")
class PostController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Post.list(params), model:[postInstanceCount: Post.count()]
    }

    def show(Post postInstance) {
        respond postInstance
    }

    def create() {
        respond new Post(params)
    }

    @Transactional
    def save(Post postInstance) {
        if (postInstance == null) {
            notFound()
            return
        }

        if (postInstance.hasErrors()) {
            respond postInstance.errors, view:'create'
            return
        }

        postInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'post.label', default: 'Post'), postInstance.id])
                redirect postInstance
            }
            '*' { respond postInstance, [status: CREATED] }
        }
    }

    def edit(Post postInstance) {
        respond postInstance
    }

    @Transactional
    def update(Post postInstance) {
        if (postInstance == null) {
            notFound()
            return
        }

        if (postInstance.hasErrors()) {
            respond postInstance.errors, view:'edit'
            return
        }

        postInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Post.label', default: 'Post'), postInstance.id])
                redirect postInstance
            }
            '*'{ respond postInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Post postInstance) {

        if (postInstance == null) {
            notFound()
            return
        }

        postInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Post.label', default: 'Post'), postInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'post.label', default: 'Post'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/post/_form.gsp
<%@ page import="ar.piwaf.Post" %>



<div class="form-group">
	<label for="titulo">
		<g:message code="post.titulo.label" default="Titulo" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="titulo" required="" value="${postInstance?.titulo}" class="form-control" />
</div>

<div class="form-group">
	<label for="autor">
		<g:message code="post.autor.label" default="Autor" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="autor" required="" value="${postInstance?.autor}" class="form-control" />
</div>

<div class="form-group">
	<label for="contenido">
		<g:message code="post.contenido.label" default="Contenido" />
		<span class="required-indicator">*</span>
	</label>
	<g:textArea name="contenido" maxlength="500" required="" value="${postInstance?.contenido}" class="form-control" />
</div>

grails-app/views/post/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'post.label', default: 'Post')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<g:form url="[resource:postInstance, action:'save']" >
			<div class="panel panel-primary">
				<div class="panel-heading">
					<g:message code="default.create.label" args="[entityName]" />
				</div>
				<div class="panel-body">
					<g:if test="${flash.message}">
						<div class="alert alert-success alert-dismissable">
							<button type="button" class="close" data-dismiss="alert"
								aria-hidden="true">&times;</button>
							${flash.message}
						</div>
					</g:if>
					<g:hasErrors bean="${postInstance}">
					<ul class="errors" role="alert">
						<g:eachError bean="${postInstance}" var="error">
						<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
						</g:eachError>
					</ul>
					</g:hasErrors>
					<g:render template="form"/>
				</div>
				<div class="panel-footer">
					<g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</div>
			</div>
		</g:form>
	</body>
</html>

grails-app/views/post/edit.gsp
<%@ page import="ar.piwaf.Post" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'post.label', default: 'Post')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<g:form url="[resource:postInstance, action:'update']" method="PUT" >
			<g:hiddenField name="version" value="${postInstance?.version}" />
			<div class="panel panel-primary">
				<div class="panel-heading">
					<g:message code="default.edit.label" args="[entityName]" />
				</div>
				<div class="panel-body">
					<g:if test="${flash.message}">
						<div class="alert alert-success alert-dismissable">
							<button type="button" class="close" data-dismiss="alert"
								aria-hidden="true">&times;</button>
							${flash.message}
						</div>
					</g:if>
					<g:hasErrors bean="${postInstance}">
					<ul class="errors" role="alert">
						<g:eachError bean="${postInstance}" var="error">
						<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
						</g:eachError>
					</ul>
					</g:hasErrors>
					<g:render template="form"/>
				</div>
				<div class="panel-footer">
					<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</div>
			</div>
		</g:form>
	</body>
</html>

grails-app/views/post/index.gsp
<%@ page import="ar.piwaf.Post" %>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="bootstrap">
<g:set var="entityName"
	value="${message(code: 'post.label', default: 'Post')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
	<g:if test="${flash.message}">
		<div class="alert alert-success alert-dismissable">
			<button type="button" class="close" data-dismiss="alert"
				aria-hidden="true">&times;</button>
			${flash.message}
		</div>
	</g:if>
	<div class="panel panel-primary">
		<div class="panel-heading">
			<g:message code="default.list.label" args="[entityName]" />
		</div>
		<div class="panel-body">
			<table class="table table-hover">
				<thead>
					<tr>
						
							<g:sortableColumn property="titulo" title="${message(code: 'post.titulo.label', default: 'Titulo')}" />
						
							<g:sortableColumn property="autor" title="${message(code: 'post.autor.label', default: 'Autor')}" />
						
							<g:sortableColumn property="contenido" title="${message(code: 'post.contenido.label', default: 'Contenido')}" />
						
							<g:sortableColumn property="dateCreated" title="${message(code: 'post.dateCreated.label', default: 'Date Created')}" />
						
						<th>Opciones</th>
					</tr>
				</thead>
				<tbody>
					<g:each in="${postInstanceList}" status="i"
						var="postInstance">
						<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
							
								<td>${fieldValue(bean: postInstance, field: "titulo")}</td>
							
								<td>${fieldValue(bean: postInstance, field: "autor")}</td>
							
								<td>${fieldValue(bean: postInstance, field: "contenido")}</td>
							
								<td><g:formatDate date="${postInstance.dateCreated}" format="dd/MM/yyyy HH:mm" /></td>
							
							<td><g:link action="show" class="btn btn-default" id="${postInstance.id}">VER</g:link></td>
						</tr>
					</g:each>
				</tbody>
			</table>
		</div>
		<div class="panel-footer">
			<a href="${createLink(action:'create')}" class="btn btn-primary"><g:message code="default.new.label" args="[entityName]" /></a>
		</div>
	</div>
</body>
</html>

grails-app/views/post/show.gsp
<%@ page import="ar.piwaf.Post" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'post.label', default: 'Post')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="panel panel-primary">
			<div class="panel-heading">
				<g:message code="default.show.label" args="[entityName]" />
			</div>
			<div class="panel-body">
				<g:if test="${flash.message}">
					<div class="alert alert-success alert-dismissable">
						<button type="button" class="close" data-dismiss="alert"
							aria-hidden="true">&times;</button>
						${flash.message}
					</div>
				</g:if>
				
					<g:if test="${postInstance?.titulo}">
					<div class="row" style="padding-left: 15px;">
						<span style="font-weight: bold;"><g:message code="post.titulo.label" default="Título" /></span>: 
						
							<span class="property-value" aria-labelledby="titulo-label"><g:fieldValue bean="${postInstance}" field="titulo"/></span>
						
					</div>
					</g:if>
				
					<g:if test="${postInstance?.autor}">
					<div class="row" style="padding-left: 15px;">
						<span style="font-weight: bold;"><g:message code="post.autor.label" default="Autor" /></span>: 
						
							<span class="property-value" aria-labelledby="autor-label"><g:fieldValue bean="${postInstance}" field="autor"/></span>
						
					</div>
					</g:if>
				
					<g:if test="${postInstance?.contenido}">
					<div class="row" style="padding-left: 15px;">
						<span style="font-weight: bold;"><g:message code="post.contenido.label" default="Contenido" /></span>: 
						
							<span class="property-value" aria-labelledby="contenido-label"><g:fieldValue bean="${postInstance}" field="contenido"/></span>
						
					</div>
					</g:if>
				
					<g:if test="${postInstance?.dateCreated}">
					<div class="row" style="padding-left: 15px;">
						<span style="font-weight: bold;"><g:message code="post.dateCreated.label" default="Creación" /></span>: 
						
							<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${postInstance?.dateCreated}" format="dd/MM/yyyy HH:mm" /></span>
						
					</div>
					</g:if>
				
			</div>
			<div class="panel-footer">
				<g:form url="[resource:postInstance, action:'delete']" method="DELETE">
					<g:link class="btn btn-default" action="edit" resource="${postInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="btn btn-danger" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</g:form>
			</div>
		</div>
	</body>
</html>